# Generated by Django 5.0.6 on 2024-06-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_useraccount_date_joined_useraccount_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
