# Generated by Django 5.0.6 on 2024-06-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_emailverificationtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_confirmed',
            new_name='email_verified',
        ),
    ]
