# Generated by Django 5.0.6 on 2024-06-30 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_is_confirmed_useraccount_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('useraccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('companyName', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('api.useraccount',),
        ),
        migrations.CreateModel(
            name='GovermentAccount',
            fields=[
                ('useraccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('GovermentAccountName', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('api.useraccount',),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='badge',
            field=models.CharField(choices=[('2', 'badge2'), ('3', 'badge3'), ('5', 'badge5')], max_length=3, null=True),
        ),
    ]
