# Generated by Django 5.0.6 on 2024-07-02 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_voiture_date_voiture_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enchaire',
            name='buyer',
        ),
        migrations.AlterField(
            model_name='enchaire',
            name='etat',
            field=models.CharField(choices=[('1', 'upcoming'), ('2', 'active'), ('3', 'finis')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='enchaire',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enchaires_gagnée', to=settings.AUTH_USER_MODEL),
        ),
    ]
